--Task 3

-- 1. List Events and Their Average Ticket Prices
Select event_type,avg(ticket_price) from Event group by event_type

-- 2. Calculate Total Revenue Generated by Events
Select sum((total_seats-available_seats)* ticket_price) as 'Total Revenue' from Event 

-- 3. Find the event with the highest ticket sales
Select Top 1 e.event_name,max(b.num_tickets) from Booking b join Event e on 
e.event_id=b.event_id group by e.event_name order by sum(b.num_tickets) desc

-- 4. Total Number of Tickets Sold for Each Event
Select event_id,sum(num_tickets) as 'Total Number of Tickets' from Booking group by event_id 

-- 5. Find Events with No Ticket Sales
Select event_name from Event where total_seats=available_seats

-- 6. Find the User Who Has Booked the Most Tickets
Select top 1 c.customer_name ,max(b.num_tickets) from Customer c left join Booking b on
b.customer_id=c.customer_id group by c.customer_name order by max(b.num_tickets) desc 

-- 7. List Events and the total number of tickets sold for each month
Select e.event_name,sum(b.num_tickets),month(b.booking_date) from Booking b right join Event e on 
b.event_id=e.event_id group by e.event_name,month(b.booking_date),year(b.booking_date)

-- 8. Calculate the average Ticket Price for Events in Each Venue
Select venue_id,event_name,avg(ticket_price) from Event group by venue_id,event_name 

--9. Calculate the total Number of Tickets Sold for Each Event Type
Select e.event_type,sum(num_tickets) from Event e left join Booking b on 
e.event_id=b.event_id group by e.event_type

--10. Calculate the total Revenue Generated by Events in Each Year
Select year(b.booking_date),sum((e.total_seats-e.available_seats)*e.ticket_price) from Booking b left join 
Event e on e.event_id=b.event_id group by year(b.booking_date)

--11. List users who have booked tickets for multiple events 
Select c.customer_name from Customer c left join Booking b on c.customer_id=b.customer_id
group by c.customer_name having count(c.customer_id)>1

--12. Calculate the Total Revenue Generated by Events for Each User
Select c.customer_name,sum(b.num_tickets*e.ticket_price) as 'Revenue from Each User' from Customer c left join 
Booking b on c.customer_id=b.customer_id left join Event e on e.event_id=b.event_id
group by c.customer_name

--13. Calculate the Average Ticket Price for Events in Each Category and Venue
Select e.event_type,v.venue_name,avg(e.ticket_price) from Event e left join Venue v
on e.venue_id=v.venue_id group by e.event_type,v.venue_name

--14.  List Users and the Total Number of Tickets They've Purchased in the Last 30 Days
Select c.customer_name,sum(b.num_tickets) from Booking b left join Customer c 
on b.customer_id=c.customer_id where booking_date>=dateadd(DAY,-30,getdate())  group by c.customer_name 
